namespace Hollow.Data.Definitions
{
    public enum AudioCueId
    {
        ProjectileFire,
        EnemyHit,
        EnemyDeath,
        PlayerHit,
        RewardClaim,
        DoorUnlock,
        RoomClear,
        PortalComplete,
        DesignerPlace,
        DesignerErase,
        PlayerInvulnerable,
        KnockbackImpact,
        EnemyWindup,
        EnemyCorpseGhost,
        DamageBlocked,
        ShieldGuardStart,
        ShieldBlock,
        ShieldParryCounter,
        ShieldUnavailable,
        HazardHit,
        BarrelBreak,
        BarrelExplode,
        HazardCoinDrop,
        ChestOpen,
        CoinPickup,
        PlayerRollStart
    }
}
