using System;
using System.Collections.Generic;
using System.Linq;
using Hollow.Data.Definitions;

namespace Hollow.Combat
{
    public static class EnemyAttackProfileDefaults
    {
        private const float DefaultGuardRecoil = 0.35f;

        public static IReadOnlyList<EnemyAttackProfileSpec> AllEnemySpecs { get; } = new[]
        {
            Enemy("spawnEnemyNormal", "claw_lunge", "Claw Lunge", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.15f, 0.22f, 0.18f, 1.4f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "Primary M75 lunge profile."),
            Enemy("spawnEnemyNormal", "desperate_bite", "Desperate Bite", EnemyAttackRuntimeKind.Contact, 1, 1f, 0f, 0.1f, 0.7f, 0, 0f, DamageChannel.Physical, DamageDelivery.Contact, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.3f, "Fallback body/contact bite."),
            Enemy("spawnEnemyNormal", "short_backstep", "Short Backstep", EnemyAttackRuntimeKind.CreatureMove, 0, 0.9f, 0.08f, 0.22f, 2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 non-damaging reset hop; ordinary overlap remains harmless.", recoverySeconds: 0.16f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.72f),
            Enemy("spawnEnemyNormal", "warning_feint", "Warning Feint", EnemyAttackRuntimeKind.CreatureSignal, 0, 1.25f, 0.16f, 0.12f, 2.4f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 non-damaging shoulder feint that telegraphs pressure without passive contact damage.", recoverySeconds: 0.2f, hitArcDegrees: 120f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyFlying", "panic_peck", "Panic Peck", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.15f, 0.18f, 0.16f, 1.35f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.25f, "Prey panic lunge when endangered."),
            Enemy("spawnEnemyFlying", "dive_scratch", "Dive Scratch", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.25f, 0.22f, 0.18f, 1.35f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.45f, "Sharper engaged dive; no new pathfinding."),
            Enemy("spawnEnemyFlying", "wing_buffet", "Wing Buffet", EnemyAttackRuntimeKind.Area, 1, 1.8f, 0.28f, 0.18f, 1.05f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.5f, "Catalogue pressure profile for close-range shove."),
            Enemy("spawnEnemyFlying", "fly_strafe", "Fly Strafe", EnemyAttackRuntimeKind.CreatureMove, 0, 0.85f, 0.06f, 0.28f, 4.5f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 lateral flying reposition with no hit window.", recoverySeconds: 0.12f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.95f),
            Enemy("spawnEnemyFlying", "dive_feint", "Dive Feint", EnemyAttackRuntimeKind.CreatureSignal, 0, 1.15f, 0.14f, 0.12f, 3f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 false dive tell; prey identity stays readable.", recoverySeconds: 0.18f, hitArcDegrees: 120f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyFast", "quick_pounce", "Quick Pounce", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.05f, 0.18f, 0.16f, 1.25f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.3f, "Fast primary lunge."),
            Enemy("spawnEnemyFast", "side_pounce", "Side Pounce", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.2f, 0.2f, 0.17f, 1.45f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.38f, "M82 committed lateral pounce prototype.", recoverySeconds: 0.2f, hitArcDegrees: 120f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyFast", "needle_rush", "Needle Rush", EnemyAttackRuntimeKind.Contact, 1, 0.85f, 0f, 0.12f, 0.65f, 0, 0f, DamageChannel.Physical, DamageDelivery.Contact, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.45f, "Contact pressure while weaving through the player."),
            Enemy("spawnEnemyFast", "snap_followup", "Snap Followup", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.35f, 0.16f, 0.12f, 1.05f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.25f, "Short fallback bite profile."),
            Enemy("spawnEnemyFast", "evasive_skitter", "Evasive Skitter", EnemyAttackRuntimeKind.CreatureMove, 0, 0.8f, 0.06f, 0.22f, 2.2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 diagonal skitter that creates a whiff/punish rhythm.", recoverySeconds: 0.12f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.85f),
            Enemy("spawnEnemyFast", "snap_combo", "Snap Combo", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.25f, 0.14f, 0.12f, 1.15f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.24f, "M85 body-only snap option; still one active hit window.", recoverySeconds: 0.2f, hitArcDegrees: 130f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.45f),
            Enemy("spawnEnemyHeavy", "body_slam", "Body Slam", EnemyAttackRuntimeKind.Contact, 2, 1.1f, 0f, 0.14f, 0.8f, 0, 0f, DamageChannel.Physical, DamageDelivery.Contact, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.Heavy, 0.75f, "High-stability contact threat."),
            Enemy("spawnEnemyHeavy", "stomp", "Stomp", EnemyAttackRuntimeKind.Area, 2, 2.2f, 0.42f, 0.18f, 1.25f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.Heavy, 0.85f, "M82 heavy circular stomp prototype with high guard pressure.", recoverySeconds: 0.38f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Heavy),
            Enemy("spawnEnemyHeavy", "maul_lunge", "Maul Lunge", EnemyAttackRuntimeKind.MeleeLunge, 2, 1.35f, 0.28f, 0.2f, 1.7f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.Heavy, 0.7f, "Slow readable heavy lunge."),
            Enemy("spawnEnemyHeavy", "heavy_shove", "Heavy Shove", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.45f, 0.24f, 0.16f, 1.25f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.6f, "Lower-damage control hit."),
            Enemy("spawnEnemyHeavy", "guarded_shove", "Guarded Shove", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.55f, 0.3f, 0.16f, 1.55f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.62f, "M85 braced shove; a readable check rather than passive body contact.", recoverySeconds: 0.34f, hitArcDegrees: 110f, poiseBreakThreshold: ImpactForceClass.Medium, activeMovementDistanceMeters: 0.28f),
            Enemy("spawnEnemyHeavy", "slow_overhead_slam", "Slow Overhead Slam", EnemyAttackRuntimeKind.Area, 2, 2.45f, 0.52f, 0.2f, 1.45f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.Heavy, 0.9f, "M85 slow body-only slam with long punishable recovery.", recoverySeconds: 0.55f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Heavy),
            Enemy("spawnEnemyCharger", "ash_charge", "Ash Charge", EnemyAttackRuntimeKind.Charge, 1, 2f, 0.42f, 0.38f, 5.5f, 0, 0f, DamageChannel.Elemental, DamageDelivery.Contact, DamageElement.Fire, ImpactForceClass.Heavy, DamageThreatKind.Heavy, 0.8f, "Existing charge with explicit fire identity."),
            Enemy("spawnEnemyCharger", "ember_clash", "Ember Clash", EnemyAttackRuntimeKind.Contact, 1, 1f, 0f, 0.12f, 0.7f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.5f, "Fallback body clash outside active charge."),
            Enemy("spawnEnemyCharger", "short_recover_hop", "Short Recover Hop", EnemyAttackRuntimeKind.CreatureMove, 0, 1.05f, 0.08f, 0.22f, 1.8f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 short reset after close pressure or a whiff.", recoverySeconds: 0.18f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.78f),
            Enemy("spawnEnemyCharger", "shoulder_check", "Shoulder Check", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.45f, 0.24f, 0.15f, 1.25f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.55f, "M85 close physical check when the charge line is too tight.", recoverySeconds: 0.32f, hitArcDegrees: 95f, poiseBreakThreshold: ImpactForceClass.Medium, activeMovementDistanceMeters: 0.38f),
            Enemy("spawnEnemyTurret", "bone_dart", "Bone Dart", EnemyAttackRuntimeKind.Projectile, 1, 1.35f, 0.34f, 0.1f, 8f, 1, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "Standard sentinel shot."),
            Enemy("spawnEnemyTurret", "braced_spike", "Braced Spike", EnemyAttackRuntimeKind.Projectile, 1, 1.8f, 0.42f, 0.1f, 8f, 1, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.48f, "Slower stronger ranged shot."),
            Enemy("spawnEnemyTurret", "rattle_volley", "Rattle Volley", EnemyAttackRuntimeKind.Projectile, 1, 1.6f, 0.34f, 0.1f, 8f, 3, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.3f, "Catalogue volley profile; current runtime fires one projectile in V1."),
            Enemy("spawnEnemySplitter", "husk_cleave", "Husk Cleave", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.25f, 0.22f, 0.18f, 1.45f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.5f, "Basic predator cleave."),
            Enemy("spawnEnemySplitter", "splinter_lunge", "Splinter Lunge", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.15f, 0.22f, 0.18f, 1.6f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.45f, "Primary M75 splitter lunge."),
            Enemy("spawnEnemySplitter", "death_split", "Death Split", EnemyAttackRuntimeKind.Split, 0, 0.1f, 0f, 0.1f, 1.2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.35f, "Metadata/runtime event profile for split children."),
            Enemy("spawnEnemySplitter", "splitter_backstep", "Splitter Backstep", EnemyAttackRuntimeKind.CreatureMove, 0, 0.95f, 0.08f, 0.22f, 2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 short backstep that frames the next cleave.", recoverySeconds: 0.16f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.8f),
            Enemy("spawnEnemySplitter", "cleave_feint", "Cleave Feint", EnemyAttackRuntimeKind.CreatureSignal, 0, 1.2f, 0.18f, 0.12f, 2.2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 non-damaging cleave tell used to bait a dodge.", recoverySeconds: 0.22f, hitArcDegrees: 120f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemySpittingPod", "spit_lob", "Spit Lob", EnemyAttackRuntimeKind.Projectile, 1, 1f, 0.24f, 0.85f, 8f, 1, 5f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "Visible ballistic lob that lands as a small splash where the player was targeted."),
            Enemy("spawnEnemyRat", "warning_squeal", "Warning Squeal", EnemyAttackRuntimeKind.Movement, 0, 0.9f, 0.25f, 0.1f, 2.5f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M82/M85 non-damaging territorial warning before bite commitment.", recoverySeconds: 0.1f, hitArcDegrees: 220f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyRat", "rat_bite", "Rat Bite", EnemyAttackRuntimeKind.MeleeLunge, 1, 0.9f, 0.14f, 0.14f, 0.95f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.22f, "Territorial close bite after warning or disturbance."),
            Enemy("spawnEnemyRat", "skitter_retreat", "Skitter Retreat", EnemyAttackRuntimeKind.CreatureMove, 0, 0.75f, 0.06f, 0.22f, 2.2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 fast retreat burst after damage or threat.", recoverySeconds: 0.12f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.9f),
            Enemy("spawnEnemyRat", "panic_pounce", "Panic Pounce", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.05f, 0.16f, 0.14f, 1.2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.28f, "M85 territorial panic leap after warning fails.", recoverySeconds: 0.18f, hitArcDegrees: 120f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.7f),
            Enemy("spawnEnemyRat", "alarm_squeal", "Alarm Squeal", EnemyAttackRuntimeKind.CreatureSignal, 0, 1.6f, 0.18f, 0.12f, 5f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 same-family signal affecting nearby living rats only.", recoverySeconds: 0.28f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemySpider", "startle_hop", "Startle Hop", EnemyAttackRuntimeKind.MeleeLunge, 1, 0.85f, 0.12f, 0.16f, 1.15f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.3f, "Chaotic hop-forward attack chosen after startle."),
            Enemy("spawnEnemySpider", "close_bite", "Close Bite", EnemyAttackRuntimeKind.MeleeLunge, 1, 0.75f, 0.1f, 0.12f, 0.75f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.22f, "Very close panic bite."),
            Enemy("spawnEnemySpider", "side_hop_bite", "Side Hop Bite", EnemyAttackRuntimeKind.MeleeLunge, 1, 0.9f, 0.12f, 0.14f, 1.1f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.26f, "M82 quick side-hop bite prototype.", recoverySeconds: 0.14f, hitArcDegrees: 125f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemySpider", "panic_flee", "Panic Flee", EnemyAttackRuntimeKind.CreatureMove, 0, 0.7f, 0.05f, 0.22f, 2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 erratic non-damaging flee burst.", recoverySeconds: 0.1f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 1.0f),
            Enemy("spawnEnemySpider", "web_feint", "Web Feint", EnemyAttackRuntimeKind.CreatureSignal, 0, 1.1f, 0.12f, 0.12f, 2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 non-damaging rear-up feint; no web slow or status effect.", recoverySeconds: 0.16f, hitArcDegrees: 180f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyHollowBird", "swoop_peck", "Swoop Peck", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.1f, 0.18f, 0.15f, 1.35f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.26f, "M85 Hollow Bird committed swoop-peck.", recoverySeconds: 0.22f, hitArcDegrees: 110f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 1f),
            Enemy("spawnEnemyHollowBird", "claw_dive", "Claw Dive", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.35f, 0.24f, 0.17f, 1.55f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.38f, "M85 Hollow Bird heavier dive with clear recovery.", recoverySeconds: 0.28f, hitArcDegrees: 100f, poiseBreakThreshold: ImpactForceClass.Medium, activeMovementDistanceMeters: 1.15f),
            Enemy("spawnEnemyHollowBird", "wing_retreat", "Wing Retreat", EnemyAttackRuntimeKind.CreatureMove, 0, 1f, 0.08f, 0.25f, 3.8f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 flying local burst away from pressure.", recoverySeconds: 0.15f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 1.25f),
            Enemy("spawnEnemyHollowBird", "caw_signal", "Caw Signal", EnemyAttackRuntimeKind.CreatureSignal, 0, 2f, 0.22f, 0.12f, 5.2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 same-family signal affecting nearby living Hollow Birds only.", recoverySeconds: 0.25f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyHollowBeast", "leap_bite", "Leap Bite", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.15f, 0.22f, 0.16f, 1.45f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "M85 Hollow Beast punish leap bite.", recoverySeconds: 0.28f, hitArcDegrees: 115f, poiseBreakThreshold: ImpactForceClass.Medium, activeMovementDistanceMeters: 0.9f),
            Enemy("spawnEnemyHollowBeast", "body_check", "Body Check", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.45f, 0.3f, 0.18f, 1.65f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.55f, "M85 grounded beast shoulder/body check with punishable recovery.", recoverySeconds: 0.38f, hitArcDegrees: 100f, poiseBreakThreshold: ImpactForceClass.Medium, activeMovementDistanceMeters: 0.75f),
            Enemy("spawnEnemyHollowBeast", "leap_back", "Leap Back", EnemyAttackRuntimeKind.CreatureMove, 0, 1.05f, 0.1f, 0.24f, 2.2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 grounded local retreat burst.", recoverySeconds: 0.2f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 1f),
            Enemy("spawnEnemyHollowBeast", "howl_signal", "Howl Signal", EnemyAttackRuntimeKind.CreatureSignal, 0, 2.2f, 0.28f, 0.14f, 5.5f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M85 same-family signal affecting nearby living Hollow Beasts only.", recoverySeconds: 0.35f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemySkeletonSword", "rusty_slash", "Rusty Slash", EnemyAttackRuntimeKind.WeaponMelee, 1, 1.35f, 0.28f, 0.14f, 1.45f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "M84 sword skeleton opener; can chain once into backhand slash.", recoverySeconds: 0.24f, hitArcDegrees: 120f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0f, comboFollowUpAttackId: "backhand_slash"),
            Enemy("spawnEnemySkeletonSword", "backhand_slash", "Backhand Slash", EnemyAttackRuntimeKind.WeaponMelee, 1, 1.15f, 0.18f, 0.14f, 1.35f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.3f, "M84 sword skeleton one-follow-up finisher.", recoverySeconds: 0.34f, hitArcDegrees: 140f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0f),
            Enemy("spawnEnemySkeletonSpear", "spear_thrust", "Spear Thrust", EnemyAttackRuntimeKind.WeaponMelee, 1, 1.55f, 0.34f, 0.12f, 2.4f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.45f, "M84 spear skeleton narrow reach poke with a small forward step.", recoverySeconds: 0.34f, hitArcDegrees: 55f, poiseBreakThreshold: ImpactForceClass.Medium, activeMovementDistanceMeters: 0.28f),
            Enemy("spawnEnemySkeletonSpear", "spear_sweep", "Spear Sweep", EnemyAttackRuntimeKind.WeaponMelee, 1, 1.75f, 0.3f, 0.16f, 1.65f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "M84 spear skeleton wide close-range sweep.", recoverySeconds: 0.38f, hitArcDegrees: 160f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0f),
            Enemy("spawnEnemyKnight", "shield_guard", "Shield Guard", EnemyAttackRuntimeKind.Defense, 0, 1.25f, 0.12f, 0.65f, 2.25f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Light, 0f, "M84 medium-shield frontal guard window.", recoverySeconds: 0.28f, hitArcDegrees: 150f, poiseBreakThreshold: ImpactForceClass.Heavy, activeMovementDistanceMeters: 0f),
            Enemy("spawnEnemyKnight", "knight_slash", "Knight Slash", EnemyAttackRuntimeKind.WeaponMelee, 1, 1.6f, 0.36f, 0.16f, 1.65f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.5f, "M84 knight committed slash; can chain once into shield bash.", recoverySeconds: 0.36f, hitArcDegrees: 120f, poiseBreakThreshold: ImpactForceClass.Medium, activeMovementDistanceMeters: 0.08f, comboFollowUpAttackId: "shield_bash"),
            Enemy("spawnEnemyKnight", "knight_thrust", "Knight Thrust", EnemyAttackRuntimeKind.WeaponMelee, 1, 1.55f, 0.34f, 0.13f, 2.15f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.45f, "M84 knight narrow forward thrust.", recoverySeconds: 0.38f, hitArcDegrees: 65f, poiseBreakThreshold: ImpactForceClass.Medium, activeMovementDistanceMeters: 0.22f),
            Enemy("spawnEnemyKnight", "shield_bash", "Shield Bash", EnemyAttackRuntimeKind.WeaponMelee, 1, 1.85f, 0.28f, 0.14f, 1.15f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.65f, "M84 knight short control hit and combo finisher.", recoverySeconds: 0.5f, hitArcDegrees: 90f, poiseBreakThreshold: ImpactForceClass.Heavy, activeMovementDistanceMeters: 0.2f),
            Enemy("spawnEnemyGiant", "club_sweep", "Club Sweep", EnemyAttackRuntimeKind.WeaponMelee, 2, 2.65f, 0.65f, 0.22f, 2.25f, 0, 0f, DamageChannel.Physical, DamageDelivery.Melee, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.Heavy, 0.9f, "M84 giant slow elite sweeping punish.", recoverySeconds: 0.75f, hitArcDegrees: 190f, poiseBreakThreshold: ImpactForceClass.Heavy, activeMovementDistanceMeters: 0.08f),
            Enemy("spawnEnemyGiant", "overhead_slam", "Overhead Slam", EnemyAttackRuntimeKind.Area, 2, 3.15f, 0.78f, 0.2f, 1.55f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.Heavy, 1.1f, "M84 giant circular impact slam.", recoverySeconds: 0.9f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Heavy),
            Enemy("spawnEnemyGiant", "stomp", "Giant Stomp", EnemyAttackRuntimeKind.Area, 1, 2.35f, 0.5f, 0.18f, 1.25f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.Heavy, 0.8f, "M84 giant shorter area punish.", recoverySeconds: 0.6f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyHollowArcher", "arrow_shot", "Arrow Shot", EnemyAttackRuntimeKind.Projectile, 1, 1.55f, 0.38f, 0.08f, 7.5f, 1, 6.3f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "M86 bow shot: draw, release, and punishable recovery.", recoverySeconds: 0.38f, hitArcDegrees: 45f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyHollowArcher", "retreating_arrow", "Retreating Arrow", EnemyAttackRuntimeKind.Projectile, 1, 1.9f, 0.34f, 0.08f, 6.7f, 1, 6f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.32f, "M86 bow shot used after spacing pressure.", recoverySeconds: 0.42f, hitArcDegrees: 50f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyHollowArcher", "arrow_volley", "Arrow Volley", EnemyAttackRuntimeKind.FanProjectile, 1, 2.35f, 0.48f, 0.08f, 7.25f, 3, 5.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.32f, "M86 three-arrow fan with visible gaps.", recoverySeconds: 0.46f, hitArcDegrees: 36f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyHollowArcher", "archer_backstep", "Archer Backstep", EnemyAttackRuntimeKind.CreatureMove, 0, 1.05f, 0.08f, 0.2f, 2.5f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M86 non-damaging ranged spacing reset.", recoverySeconds: 0.2f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.85f),
            Enemy("spawnEnemyPowderGunner", "aimed_musket_shot", "Aimed Musket Shot", EnemyAttackRuntimeKind.Projectile, 2, 2.4f, 0.72f, 0.06f, 8.8f, 1, 10f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.StrongProjectile, 0.75f, "M86 firearm: long aim lock, fast projectile, heavy guard pressure.", recoverySeconds: 0.75f, hitArcDegrees: 28f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyPowderGunner", "scatter_shot", "Scatter Shot", EnemyAttackRuntimeKind.FanProjectile, 1, 2.8f, 0.58f, 0.08f, 5.4f, 5, 7f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.45f, "M86 close-range firearm fan with broad but dodgeable lanes.", recoverySeconds: 0.68f, hitArcDegrees: 58f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyPowderGunner", "gunner_backstep", "Gunner Backstep", EnemyAttackRuntimeKind.CreatureMove, 0, 1.25f, 0.12f, 0.2f, 2.5f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M86 slow reload-space hop with no damage.", recoverySeconds: 0.26f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.7f),
            Enemy("spawnEnemyKnifeThrower", "throwing_knife", "Throwing Knife", EnemyAttackRuntimeKind.Projectile, 1, 1.1f, 0.22f, 0.06f, 5.8f, 1, 7f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.24f, "M86 quick mid-range knife throw.", recoverySeconds: 0.24f, hitArcDegrees: 80f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyKnifeThrower", "knife_fan", "Knife Fan", EnemyAttackRuntimeKind.FanProjectile, 1, 1.9f, 0.34f, 0.08f, 4.8f, 3, 6.5f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.26f, "M86 three-knife pressure fan.", recoverySeconds: 0.32f, hitArcDegrees: 42f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyKnifeThrower", "thrower_backstep", "Thrower Backstep", EnemyAttackRuntimeKind.CreatureMove, 0, 0.9f, 0.06f, 0.18f, 2.1f, 0, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M86 agile spacing burst for a ranged skirmisher.", recoverySeconds: 0.16f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.9f),
            Enemy("spawnEnemyRepeaterTurret", "repeater_burst", "Repeater Burst", EnemyAttackRuntimeKind.FanProjectile, 1, 1.75f, 0.36f, 0.08f, 8.5f, 3, 6.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.3f, "M86 narrow three-shot turret burst.", recoverySeconds: 0.35f, hitArcDegrees: 22f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyRepeaterTurret", "suppressing_arc", "Suppressing Arc", EnemyAttackRuntimeKind.FanProjectile, 1, 2.6f, 0.52f, 0.08f, 8f, 5, 5.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.28f, "M86 wide stationary fan with readable gaps.", recoverySeconds: 0.5f, hitArcDegrees: 78f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyRepeaterTurret", "lock_on_dart", "Lock-On Dart", EnemyAttackRuntimeKind.Projectile, 1, 1.35f, 0.42f, 0.06f, 9.25f, 1, 7.2f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.34f, "M86 precise sentinel shot after a lock-on tell.", recoverySeconds: 0.32f, hitArcDegrees: 42f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyClockworkSentry", "clockwork_radial", "Clockwork Radial", EnemyAttackRuntimeKind.RadialProjectile, 1, 2.45f, 0.55f, 0.1f, 6.5f, 8, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.42f, "M86 machine radial pattern that asks the player to find a gap.", recoverySeconds: 0.55f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyClockworkSentry", "rotating_fan", "Rotating Fan", EnemyAttackRuntimeKind.FanProjectile, 1, 1.95f, 0.38f, 0.08f, 7f, 5, 5f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.3f, "M86 rotating fan volley from a slow machine.", recoverySeconds: 0.42f, hitArcDegrees: 85f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyClockworkSentry", "gear_shot", "Gear Shot", EnemyAttackRuntimeKind.Projectile, 1, 1.4f, 0.3f, 0.06f, 7.8f, 1, 5.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.32f, "M86 simple machine projectile used between patterns.", recoverySeconds: 0.3f, hitArcDegrees: 70f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyHollowAcolyte", "slow_soul_orb", "Slow Soul Orb", EnemyAttackRuntimeKind.Projectile, 1, 1.75f, 0.48f, 0.09f, 7.2f, 1, 3.8f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Soul, ImpactForceClass.Light, DamageThreatKind.Light, 0.32f, "M87 slow caster orb with a readable cast point and generous sidestep counter.", recoverySeconds: 0.42f, hitArcDegrees: 80f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyHollowAcolyte", "rune_burst", "Rune Burst", EnemyAttackRuntimeKind.RadialProjectile, 1, 2.85f, 0.62f, 0.1f, 5.8f, 6, 4.2f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Soul, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.42f, "M87 radial soul pattern used when the player pressures the caster.", recoverySeconds: 0.58f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyHollowAcolyte", "veil_step", "Veil Step", EnemyAttackRuntimeKind.PhaseMove, 0, 1.65f, 0.12f, 0.24f, 3.2f, 0, 0f, DamageChannel.Elemental, DamageDelivery.Area, DamageElement.Soul, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M87 non-damaging phase retreat that repositions locally without pathfinding.", recoverySeconds: 0.24f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 1.05f),
            Enemy("spawnEnemyWraith", "phase_shift", "Phase Shift", EnemyAttackRuntimeKind.PhaseMove, 0, 1.45f, 0.08f, 0.26f, 4.4f, 0, 0f, DamageChannel.Elemental, DamageDelivery.Area, DamageElement.Soul, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M87 ghost reposition with a transparency-style tell and no damage.", recoverySeconds: 0.16f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 1.35f),
            Enemy("spawnEnemyWraith", "wraith_bolt", "Wraith Bolt", EnemyAttackRuntimeKind.Projectile, 1, 1.35f, 0.32f, 0.07f, 6.4f, 1, 5.2f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Soul, ImpactForceClass.Light, DamageThreatKind.Light, 0.3f, "M87 quick soul projectile after phase or side pressure.", recoverySeconds: 0.28f, hitArcDegrees: 95f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyWraith", "curse_touch", "Curse Touch", EnemyAttackRuntimeKind.MeleeLunge, 1, 1.2f, 0.2f, 0.14f, 1.25f, 0, 0f, DamageChannel.Elemental, DamageDelivery.Melee, DamageElement.Cursed, ImpactForceClass.Light, DamageThreatKind.Light, 0.28f, "M87 short active-window ghost touch; ordinary overlap remains harmless.", recoverySeconds: 0.24f, hitArcDegrees: 130f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.42f),
            Enemy("spawnEnemySoulEater", "soul_drain", "Soul Drain", EnemyAttackRuntimeKind.Beam, 1, 2.15f, 0.62f, 0.16f, 4.8f, 0, 0f, DamageChannel.Elemental, DamageDelivery.Area, DamageElement.Soul, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.48f, "M87 committed lane drain: dodge perpendicular during the cast lock.", recoverySeconds: 0.62f, hitArcDegrees: 46f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemySoulEater", "soul_burst", "Soul Burst", EnemyAttackRuntimeKind.RadialProjectile, 1, 2.65f, 0.5f, 0.1f, 5.2f, 8, 4.3f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Soul, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.45f, "M87 radial soul release that creates readable gaps around the eater.", recoverySeconds: 0.52f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemySoulEater", "eater_phase_step", "Eater Phase Step", EnemyAttackRuntimeKind.PhaseMove, 0, 1.9f, 0.14f, 0.22f, 3.6f, 0, 0f, DamageChannel.Elemental, DamageDelivery.Area, DamageElement.Soul, ImpactForceClass.Light, DamageThreatKind.Light, 0f, "M87 short non-damaging phase sidestep to set up drain angle.", recoverySeconds: 0.28f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Light, activeMovementDistanceMeters: 0.9f),
            Enemy("spawnEnemyCurseBinder", "binding_bolt", "Binding Bolt", EnemyAttackRuntimeKind.Projectile, 1, 1.65f, 0.42f, 0.08f, 7.4f, 1, 4.8f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Cursed, ImpactForceClass.Light, DamageThreatKind.Light, 0.3f, "M87 cursed straight projectile for territorial pressure.", recoverySeconds: 0.4f, hitArcDegrees: 75f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyCurseBinder", "curse_field", "Curse Field", EnemyAttackRuntimeKind.Area, 1, 3.1f, 0.78f, 0.22f, 2.35f, 0, 0f, DamageChannel.Elemental, DamageDelivery.Area, DamageElement.Cursed, ImpactForceClass.Heavy, DamageThreatKind.Heavy, 0.62f, "M87 circular curse area: leave the sigil, then punish the long recovery.", recoverySeconds: 0.78f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Heavy),
            Enemy("spawnEnemyCurseBinder", "sigil_fan", "Sigil Fan", EnemyAttackRuntimeKind.FanProjectile, 1, 2.45f, 0.58f, 0.08f, 6.8f, 5, 4.4f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Cursed, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.4f, "M87 fan of curse marks with visible lanes between shots.", recoverySeconds: 0.56f, hitArcDegrees: 82f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyGraveLantern", "lantern_soul_ring", "Lantern Soul Ring", EnemyAttackRuntimeKind.RadialProjectile, 1, 2.3f, 0.48f, 0.1f, 6.4f, 10, 3.8f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Soul, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.38f, "M87 stationary soul ring pattern with slow projectile lanes.", recoverySeconds: 0.48f, hitArcDegrees: 360f, poiseBreakThreshold: ImpactForceClass.Medium),
            Enemy("spawnEnemyGraveLantern", "lantern_curse_fan", "Lantern Curse Fan", EnemyAttackRuntimeKind.FanProjectile, 1, 2.65f, 0.56f, 0.08f, 7.6f, 5, 4.2f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Cursed, ImpactForceClass.Light, DamageThreatKind.Light, 0.32f, "M87 stationary curse fan that asks for lane reading instead of contact avoidance.", recoverySeconds: 0.52f, hitArcDegrees: 95f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyGraveLantern", "grave_orb", "Grave Orb", EnemyAttackRuntimeKind.Projectile, 1, 1.5f, 0.36f, 0.08f, 8.5f, 1, 4.6f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Soul, ImpactForceClass.Light, DamageThreatKind.Light, 0.3f, "M87 simple lantern shot between pattern casts.", recoverySeconds: 0.34f, hitArcDegrees: 120f, poiseBreakThreshold: ImpactForceClass.Light),
            Enemy("spawnEnemyBoss", "stone_charge", "Stone Warden Contact", EnemyAttackRuntimeKind.Contact, 2, 3.2f, 0.5f, 0.22f, 2.2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Contact, DamageElement.None, ImpactForceClass.Massive, DamageThreatKind.Boss, 0.9f, "Legacy generic boss spawn fallback contact profile."),
            Enemy("spawnEnemyBoss", "stone_four_way_burst", "Stone Warden Burst Shards", EnemyAttackRuntimeKind.RadialProjectile, 1, 3.8f, 0.45f, 0.1f, 6f, 4, 4.5f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.StrongProjectile, 0.55f, "Legacy generic boss spawn fallback low-health burst.")
        };

        public static IReadOnlyList<EnemyAttackProfileSpec> AllBossSpecs { get; } = new[]
        {
            Boss("stone_warden", "stone_charge", "Stone Charge", EnemyAttackRuntimeKind.Charge, 1, 3.2f, 0.5f, 0.22f, 2.2f, 0, 0f, DamageChannel.Physical, DamageDelivery.Contact, DamageElement.None, ImpactForceClass.Massive, DamageThreatKind.Boss, 0.9f, "Stone Warden dash contact."),
            Boss("stone_warden", "stone_stomp_burst", "Stone Stomp Burst", EnemyAttackRuntimeKind.RadialProjectile, 2, 4.6f, 0.55f, 0.1f, 6f, 8, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.Boss, 0.65f, "Radial stomp debris."),
            Boss("stone_warden", "stone_four_way_burst", "Stone Four-Way Burst", EnemyAttackRuntimeKind.RadialProjectile, 1, 3.8f, 0.45f, 0.1f, 6f, 4, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.StrongProjectile, 0.55f, "Low-health cardinal burst."),
            Boss("splinter_saint", "splinter_side_hop_radial", "Side-Hop Radial", EnemyAttackRuntimeKind.RadialProjectile, 1, 1.75f, 0.2f, 0.1f, 5f, 6, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "Side hop shot ring."),
            Boss("gravel_maw", "gravel_burrow_summon", "Burrow Summon", EnemyAttackRuntimeKind.Summon, 0, 7f, 0.5f, 0.1f, 1.2f, 3, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.35f, "Summons a small gravel pack."),
            Boss("gravel_maw", "gravel_rubble_spray", "Rubble Spray", EnemyAttackRuntimeKind.RadialProjectile, 1, 7f, 0.3f, 0.1f, 5f, 5, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "Rubble spray after summon."),
            Boss("cartouche_widow", "cartouche_falling_marks", "Falling Marks", EnemyAttackRuntimeKind.FanProjectile, 1, 1.65f, 0.25f, 0.1f, 6f, 5, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "Fan pressure pattern."),
            Boss("iron_reliquary", "iron_peek_shot", "Peek Shot", EnemyAttackRuntimeKind.FanProjectile, 1, 1.9f, 0.25f, 0.1f, 6f, 3, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "Three-shot cover peek."),
            Boss("iron_reliquary", "iron_relocate_bash", "Relocate Bash", EnemyAttackRuntimeKind.Movement, 1, 4.2f, 0.1f, 0.22f, 1.1f, 0, 0f, DamageChannel.Physical, DamageDelivery.Contact, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.Heavy, 0.55f, "Retreat bash profile for relocate movement."),
            Boss("mirror_husk", "mirror_chase_contact", "Mirror Chase Contact", EnemyAttackRuntimeKind.Contact, 1, 1f, 0f, 0.1f, 0.8f, 0, 0f, DamageChannel.Physical, DamageDelivery.Contact, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.Boss, 0.55f, "Chase contact body profile."),
            Boss("mirror_husk", "mirror_split", "Mirror Split", EnemyAttackRuntimeKind.Split, 0, 0.1f, 0f, 0.1f, 1.2f, 4, 0f, DamageChannel.Physical, DamageDelivery.Area, DamageElement.None, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.35f, "Split event profile."),
            Boss("ash_comet", "ash_comet_dash", "Comet Dash", EnemyAttackRuntimeKind.Charge, 2, 2.6f, 0.25f, 0.22f, 2.2f, 0, 0f, DamageChannel.Elemental, DamageDelivery.Contact, DamageElement.Fire, ImpactForceClass.Massive, DamageThreatKind.Boss, 0.95f, "Fire-aspected dash contact."),
            Boss("ash_comet", "ash_fire_radial", "Ash Fire Radial", EnemyAttackRuntimeKind.RadialProjectile, 2, 2.6f, 0.35f, 0.1f, 6f, 8, 4.8f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Fire, ImpactForceClass.Heavy, DamageThreatKind.Boss, 0.65f, "Fire radial after dash."),
            Boss("choir_of_teeth", "choir_rotating_hymn", "Rotating Hymn", EnemyAttackRuntimeKind.RadialProjectile, 1, 2.2f, 0.3f, 0.1f, 6f, 12, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.32f, "Rotating tooth ring."),
            Boss("choir_of_teeth", "choir_tooth_storm", "Tooth Storm", EnemyAttackRuntimeKind.RadialProjectile, 2, 4.2f, 0.45f, 0.1f, 6f, 16, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.StrongProjectile, 0.6f, "Low-health dense tooth storm."),
            Boss("rust_bishop", "rust_beam", "Rust Beam", EnemyAttackRuntimeKind.FanProjectile, 2, 2.8f, 0.4f, 0.1f, 6f, 3, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Heavy, DamageThreatKind.StrongProjectile, 0.65f, "Narrow heavy fan used as beam V1."),
            Boss("rust_bishop", "rust_mine_pattern", "Mine Pattern", EnemyAttackRuntimeKind.RadialProjectile, 1, 3.6f, 0.3f, 0.1f, 5f, 6, 4.8f, DamageChannel.Physical, DamageDelivery.Projectile, DamageElement.None, ImpactForceClass.Light, DamageThreatKind.Light, 0.35f, "Radial mine-like pressure pattern."),
            Boss("hollow_star_larva", "larva_abyss_call", "Abyss Call", EnemyAttackRuntimeKind.Summon, 0, 0.1f, 0f, 0.1f, 1.2f, 3, 0f, DamageChannel.Elemental, DamageDelivery.Area, DamageElement.Cosmic, ImpactForceClass.Medium, DamageThreatKind.Heavy, 0.4f, "Cosmic summon event."),
            Boss("hollow_star_larva", "larva_starfall", "Starfall", EnemyAttackRuntimeKind.FanProjectile, 1, 2.1f, 0.3f, 0.1f, 6f, 7, 4.8f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Cosmic, ImpactForceClass.Light, DamageThreatKind.Light, 0.38f, "Cosmic fan pattern."),
            Boss("hollow_star_larva", "larva_desperation", "Desperation", EnemyAttackRuntimeKind.RadialProjectile, 2, 3.1f, 0.5f, 0.1f, 6f, 18, 4.8f, DamageChannel.Elemental, DamageDelivery.Projectile, DamageElement.Cosmic, ImpactForceClass.Heavy, DamageThreatKind.StrongProjectile, 0.65f, "Cosmic desperation storm.")
        };

        public static IReadOnlyList<EnemyAttackProfileDefinition> CreateEnemyProfiles(string spawnKind)
        {
            return AllEnemySpecs
                .Where(spec => string.Equals(spec.OwnerId, spawnKind, StringComparison.Ordinal))
                .Select(EnemyAttackProfileDefinition.CreateRuntime)
                .ToArray();
        }

        public static IReadOnlyList<EnemyAttackProfileDefinition> CreateBossProfiles(string bossId)
        {
            return AllBossSpecs
                .Where(spec => string.Equals(spec.OwnerId, bossId, StringComparison.Ordinal))
                .Select(EnemyAttackProfileDefinition.CreateRuntime)
                .ToArray();
        }

        public static EnemyAttackProfileDefinition ResolveEnemyProfile(string spawnKind, string attackId)
        {
            var spec = AllEnemySpecs.FirstOrDefault(candidate =>
                string.Equals(candidate.OwnerId, spawnKind, StringComparison.Ordinal) &&
                string.Equals(candidate.AttackId, attackId, StringComparison.Ordinal));
            return string.IsNullOrWhiteSpace(spec.AttackId) ? null : EnemyAttackProfileDefinition.CreateRuntime(spec);
        }

        public static EnemyAttackProfileDefinition ResolveBossProfile(string bossId, string attackId)
        {
            var spec = AllBossSpecs.FirstOrDefault(candidate =>
                string.Equals(candidate.OwnerId, bossId, StringComparison.Ordinal) &&
                string.Equals(candidate.AttackId, attackId, StringComparison.Ordinal));
            return string.IsNullOrWhiteSpace(spec.AttackId) ? null : EnemyAttackProfileDefinition.CreateRuntime(spec);
        }

        private static EnemyAttackProfileSpec Enemy(
            string ownerId,
            string attackId,
            string displayName,
            EnemyAttackRuntimeKind runtimeKind,
            int damage,
            float cooldownSeconds,
            float windupSeconds,
            float activeSeconds,
            float rangeMeters,
            int projectileCount,
            float projectileSpeedMetersPerSecond,
            DamageChannel channel,
            DamageDelivery delivery,
            DamageElement element,
            ImpactForceClass forceClass,
            DamageThreatKind threatKind,
            float knockbackMeters,
            string notes,
            float recoverySeconds = -1f,
            float hitArcDegrees = -1f,
            ImpactForceClass poiseBreakThreshold = ImpactForceClass.Medium,
            float activeMovementDistanceMeters = -1f,
            string comboFollowUpAttackId = "")
        {
            return new EnemyAttackProfileSpec(ownerId, false, attackId, displayName, runtimeKind, damage, cooldownSeconds, windupSeconds, activeSeconds, rangeMeters, projectileCount, projectileSpeedMetersPerSecond, channel, delivery, element, forceClass, threatKind, knockbackMeters, DefaultGuardRecoil, notes, recoverySeconds, hitArcDegrees, poiseBreakThreshold, activeMovementDistanceMeters, comboFollowUpAttackId);
        }

        private static EnemyAttackProfileSpec Boss(
            string ownerId,
            string attackId,
            string displayName,
            EnemyAttackRuntimeKind runtimeKind,
            int damage,
            float cooldownSeconds,
            float windupSeconds,
            float activeSeconds,
            float rangeMeters,
            int projectileCount,
            float projectileSpeedMetersPerSecond,
            DamageChannel channel,
            DamageDelivery delivery,
            DamageElement element,
            ImpactForceClass forceClass,
            DamageThreatKind threatKind,
            float knockbackMeters,
            string notes,
            float recoverySeconds = -1f,
            float hitArcDegrees = -1f,
            ImpactForceClass poiseBreakThreshold = ImpactForceClass.Medium,
            float activeMovementDistanceMeters = -1f,
            string comboFollowUpAttackId = "")
        {
            return new EnemyAttackProfileSpec(ownerId, true, attackId, displayName, runtimeKind, damage, cooldownSeconds, windupSeconds, activeSeconds, rangeMeters, projectileCount, projectileSpeedMetersPerSecond, channel, delivery, element, forceClass, threatKind, knockbackMeters, DefaultGuardRecoil, notes, recoverySeconds, hitArcDegrees, poiseBreakThreshold, activeMovementDistanceMeters, comboFollowUpAttackId);
        }
    }
}
