using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Hollow.Combat;
using UnityEditor;
using UnityEngine;

namespace Hollow.Editor.EnemyAiBrainStudio
{
    public static class EnemyAiBrainStudioTemplateGenerator
    {
        public const string TemplateFolder = "Assets/_Hollow/Data/EnemyAiBrainTemplates";

        [MenuItem("Hollow/Enemy Authoring/Generate Enemy AI Brain Templates")]
        public static void GenerateAssets()
        {
            Directory.CreateDirectory(TemplateFolder);
            foreach (var template in CreateRuntimeTemplates())
            {
                var path = $"{TemplateFolder}/{SanitizeFileName(template.TemplateId)}.asset";
                var existing = AssetDatabase.LoadAssetAtPath<EnemyAiBrainTemplateDefinition>(path);
                if (existing == null)
                {
                    AssetDatabase.CreateAsset(template, path);
                }
                else
                {
                    EditorUtility.CopySerialized(template, existing);
                    existing.name = template.TemplateId;
                    EditorUtility.SetDirty(existing);
                    UnityEngine.Object.DestroyImmediate(template);
                }
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        public static IReadOnlyList<EnemyAiBrainTemplateDefinition> CreateRuntimeTemplates()
        {
            return new[]
            {
                Template(
                    "brain_body_pressure",
                    "Body Pressure",
                    "Baseline Souls-lite creature/chaser brain: commits from action spacing, keeps recovery readable, and uses normal senses.",
                    EnemyAiBrainTemplateRole.BodyPressure,
                    new[] { EnemyBehaviorId.Chaser, EnemyBehaviorId.Splitter, EnemyBehaviorId.HollowBeast },
                    new[] { EnemyInstinctDisposition.Predator },
                    EnemyIntelligenceLevel.Basic,
                    EnemyInstinctDisposition.Predator,
                    false,
                    speed: 1f,
                    radius: 1f,
                    sight: 1f,
                    angle: 150f,
                    hearing: 1f,
                    sensitivity: 1f,
                    threshold: 1.05f,
                    investigate: 1.2f,
                    alert: false,
                    alertRadius: 0f,
                    alertCooldown: 2.5f,
                    alertAwareness: EnemyAwarenessState.Engaged,
                    windup: 1f,
                    active: 1f,
                    recovery: 1.05f,
                    hitArcBonus: 0f,
                    poiseOffset: 0,
                    ideal: 1f,
                    closeTolerance: 0.22f,
                    longTolerance: 0.35f,
                    pressureBias: 0.42f,
                    resets: 1,
                    notes: "Default for most body-pressure enemies. Avoid endless spacing; one reset, then commit or hold."),
                Template(
                    "brain_prey_skirmisher",
                    "Prey Skirmisher",
                    "High-sense prey brain: notices quickly, flees first, and only commits when endangered or engaged.",
                    EnemyAiBrainTemplateRole.PreySkirmisher,
                    new[] { EnemyBehaviorId.FlyingChaser, EnemyBehaviorId.Spider, EnemyBehaviorId.Wraith },
                    new[] { EnemyInstinctDisposition.Prey },
                    EnemyIntelligenceLevel.Simple,
                    EnemyInstinctDisposition.Prey,
                    false,
                    speed: 1.08f,
                    radius: 1f,
                    sight: 1.15f,
                    angle: 260f,
                    hearing: 1.2f,
                    sensitivity: 1.35f,
                    threshold: 0.72f,
                    investigate: 0.65f,
                    alert: false,
                    alertRadius: 0f,
                    alertCooldown: 2f,
                    alertAwareness: EnemyAwarenessState.Alerted,
                    windup: 0.9f,
                    active: 1f,
                    recovery: 1.12f,
                    hitArcBonus: 0f,
                    poiseOffset: -1,
                    ideal: 1.15f,
                    closeTolerance: 0.3f,
                    longTolerance: 0.45f,
                    pressureBias: 0.18f,
                    resets: 1,
                    notes: "Use for enemies that should feel alive without dogpiling. Very useful for spiders and evasive flyers."),
                Template(
                    "brain_territorial_critter",
                    "Territorial Critter",
                    "Rat-like brain: great senses, warning/feint pressure, quick retreat after damage, and limited same-family signal support.",
                    EnemyAiBrainTemplateRole.TerritorialCritter,
                    new[] { EnemyBehaviorId.Rat, EnemyBehaviorId.Spider },
                    new[] { EnemyInstinctDisposition.Territorial },
                    EnemyIntelligenceLevel.Basic,
                    EnemyInstinctDisposition.Territorial,
                    false,
                    speed: 1.05f,
                    radius: 0.95f,
                    sight: 1.1f,
                    angle: 260f,
                    hearing: 1.15f,
                    sensitivity: 1.4f,
                    threshold: 0.85f,
                    investigate: 0.8f,
                    alert: true,
                    alertRadius: 3.25f,
                    alertCooldown: 2.2f,
                    alertAwareness: EnemyAwarenessState.Alerted,
                    windup: 0.88f,
                    active: 1f,
                    recovery: 1.12f,
                    hitArcBonus: 5f,
                    poiseOffset: -1,
                    ideal: 0.95f,
                    closeTolerance: 0.25f,
                    longTolerance: 0.4f,
                    pressureBias: 0.32f,
                    resets: 1,
                    notes: "Good for creatures that warn/patrol before aggression. Same-family signals should not become squad tactics."),
                Template(
                    "brain_stationary_sentinel",
                    "Stationary Sentinel",
                    "Turret/pod brain: no movement pressure, large hearing or sight role, ranged pressure gated by budgets.",
                    EnemyAiBrainTemplateRole.StationarySentinel,
                    new[] { EnemyBehaviorId.TurretShooter, EnemyBehaviorId.SpittingPod, EnemyBehaviorId.RepeaterTurret, EnemyBehaviorId.GraveLantern },
                    new[] { EnemyInstinctDisposition.Sentinel },
                    EnemyIntelligenceLevel.Trained,
                    EnemyInstinctDisposition.Sentinel,
                    false,
                    speed: 1f,
                    radius: 1f,
                    sight: 1.05f,
                    angle: 90f,
                    hearing: 1.3f,
                    sensitivity: 1.55f,
                    threshold: 0.7f,
                    investigate: 1.6f,
                    alert: false,
                    alertRadius: 0f,
                    alertCooldown: 3f,
                    alertAwareness: EnemyAwarenessState.Alerted,
                    windup: 1.05f,
                    active: 1f,
                    recovery: 1.05f,
                    hitArcBonus: 0f,
                    poiseOffset: 0,
                    ideal: 1f,
                    closeTolerance: 0.15f,
                    longTolerance: 0.25f,
                    pressureBias: 0.05f,
                    resets: 0,
                    notes: "Stationary enemies should win through projectile shape/readability, not body contact or chasing."),
                Template(
                    "brain_weapon_user",
                    "Weapon User",
                    "Skeleton/knight brain: deliberate facing, strong action spacing, block/guard decision support, and punishable recovery.",
                    EnemyAiBrainTemplateRole.WeaponUser,
                    new[] { EnemyBehaviorId.SkeletonSword, EnemyBehaviorId.SkeletonSpear, EnemyBehaviorId.Knight },
                    new[] { EnemyInstinctDisposition.Predator, EnemyInstinctDisposition.Sentinel },
                    EnemyIntelligenceLevel.Trained,
                    EnemyInstinctDisposition.Sentinel,
                    false,
                    speed: 0.96f,
                    radius: 1f,
                    sight: 1f,
                    angle: 150f,
                    hearing: 1f,
                    sensitivity: 0.95f,
                    threshold: 1.1f,
                    investigate: 1.4f,
                    alert: false,
                    alertRadius: 0f,
                    alertCooldown: 3f,
                    alertAwareness: EnemyAwarenessState.Engaged,
                    windup: 1.06f,
                    active: 1f,
                    recovery: 1.18f,
                    hitArcBonus: 0f,
                    poiseOffset: 1,
                    ideal: 1.08f,
                    closeTolerance: 0.18f,
                    longTolerance: 0.28f,
                    pressureBias: 0.38f,
                    resets: 1,
                    notes: "Dark Souls-like weapon users should be readable, face deliberately, and be punishable after whiff/guard."),
                Template(
                    "brain_ranged_kiter",
                    "Ranged Kiter",
                    "Archer/gunner/thrower brain: one reset or backstep, then commit/hold instead of endless retreat.",
                    EnemyAiBrainTemplateRole.RangedKiter,
                    new[] { EnemyBehaviorId.HollowArcher, EnemyBehaviorId.PowderGunner, EnemyBehaviorId.KnifeThrower, EnemyBehaviorId.ClockworkSentry },
                    new[] { EnemyInstinctDisposition.Predator, EnemyInstinctDisposition.Sentinel },
                    EnemyIntelligenceLevel.Tactical,
                    EnemyInstinctDisposition.Sentinel,
                    false,
                    speed: 0.96f,
                    radius: 1f,
                    sight: 1.12f,
                    angle: 170f,
                    hearing: 1f,
                    sensitivity: 1f,
                    threshold: 1f,
                    investigate: 1.15f,
                    alert: false,
                    alertRadius: 0f,
                    alertCooldown: 3f,
                    alertAwareness: EnemyAwarenessState.Engaged,
                    windup: 1.02f,
                    active: 1f,
                    recovery: 1.14f,
                    hitArcBonus: 0f,
                    poiseOffset: 0,
                    ideal: 1.12f,
                    closeTolerance: 0.25f,
                    longTolerance: 0.45f,
                    pressureBias: 0.2f,
                    resets: 1,
                    notes: "Supports Isaac room pressure while preserving Souls-like commitment windows."),
                Template(
                    "brain_magic_caster",
                    "Magic Caster",
                    "Caster/ghost/soul brain: high intent, phase/reset support, area pressure, and cautious pressure scoring.",
                    EnemyAiBrainTemplateRole.MagicCaster,
                    new[] { EnemyBehaviorId.HollowAcolyte, EnemyBehaviorId.Wraith, EnemyBehaviorId.SoulEater, EnemyBehaviorId.CurseBinder },
                    new[] { EnemyInstinctDisposition.Sentinel, EnemyInstinctDisposition.Predator },
                    EnemyIntelligenceLevel.Tactical,
                    EnemyInstinctDisposition.Sentinel,
                    false,
                    speed: 0.94f,
                    radius: 1f,
                    sight: 1.1f,
                    angle: 190f,
                    hearing: 1.05f,
                    sensitivity: 1.08f,
                    threshold: 0.95f,
                    investigate: 1.2f,
                    alert: false,
                    alertRadius: 0f,
                    alertCooldown: 3f,
                    alertAwareness: EnemyAwarenessState.Engaged,
                    windup: 1.08f,
                    active: 1f,
                    recovery: 1.2f,
                    hitArcBonus: 0f,
                    poiseOffset: 0,
                    ideal: 1.18f,
                    closeTolerance: 0.25f,
                    longTolerance: 0.5f,
                    pressureBias: 0.16f,
                    resets: 1,
                    notes: "Area and curse pressure must stay dodgeable. Phase movement is a reset, not a free escape loop."),
                Template(
                    "brain_heavy_bruiser",
                    "Heavy Bruiser",
                    "Giant/heavy brain: slow, high-poise, low reset, long planted recovery, and high threat clarity.",
                    EnemyAiBrainTemplateRole.HeavyBruiser,
                    new[] { EnemyBehaviorId.Giant, EnemyBehaviorId.Knight, EnemyBehaviorId.Chaser },
                    new[] { EnemyInstinctDisposition.Mindless, EnemyInstinctDisposition.Sentinel, EnemyInstinctDisposition.Predator },
                    EnemyIntelligenceLevel.Basic,
                    EnemyInstinctDisposition.Mindless,
                    false,
                    speed: 0.92f,
                    radius: 1.05f,
                    sight: 0.95f,
                    angle: 120f,
                    hearing: 0.9f,
                    sensitivity: 0.85f,
                    threshold: 1.25f,
                    investigate: 1.8f,
                    alert: false,
                    alertRadius: 0f,
                    alertCooldown: 3f,
                    alertAwareness: EnemyAwarenessState.Engaged,
                    windup: 1.18f,
                    active: 1f,
                    recovery: 1.35f,
                    hitArcBonus: 5f,
                    poiseOffset: 2,
                    ideal: 1.05f,
                    closeTolerance: 0.12f,
                    longTolerance: 0.25f,
                    pressureBias: 0.55f,
                    resets: 0,
                    notes: "Bruisers are allowed to be frightening because they are slow and visibly committed."),
                Template(
                    "brain_swarm_background",
                    "Swarm Background",
                    "Low-priority swarm brain: reduced senses/timing pressure, slower updates, and lower action pressure while close threats take focus.",
                    EnemyAiBrainTemplateRole.SwarmBackground,
                    new[] { EnemyBehaviorId.Chaser, EnemyBehaviorId.Rat, EnemyBehaviorId.Spider, EnemyBehaviorId.HollowBird },
                    new[] { EnemyInstinctDisposition.Predator, EnemyInstinctDisposition.Territorial, EnemyInstinctDisposition.Prey },
                    EnemyIntelligenceLevel.Simple,
                    EnemyInstinctDisposition.Predator,
                    false,
                    speed: 0.96f,
                    radius: 1f,
                    sight: 0.9f,
                    angle: 170f,
                    hearing: 0.9f,
                    sensitivity: 0.82f,
                    threshold: 1.35f,
                    investigate: 0.95f,
                    alert: false,
                    alertRadius: 0f,
                    alertCooldown: 3f,
                    alertAwareness: EnemyAwarenessState.Alerted,
                    windup: 1.04f,
                    active: 1f,
                    recovery: 1.18f,
                    hitArcBonus: 0f,
                    poiseOffset: -1,
                    ideal: 1.08f,
                    closeTolerance: 0.28f,
                    longTolerance: 0.5f,
                    pressureBias: 0.12f,
                    resets: 1,
                    notes: "Use as a global fallback for large rooms: background enemies look alive but stop competing with the main duel."),
                Template(
                    "brain_boss_metadata",
                    "Boss Metadata",
                    "Read-only boss brain metadata until boss behavior-tree runtime is explicitly enabled later.",
                    EnemyAiBrainTemplateRole.BossMetadata,
                    Array.Empty<EnemyBehaviorId>(),
                    new[] { EnemyInstinctDisposition.Sentinel },
                    EnemyIntelligenceLevel.Tactical,
                    EnemyInstinctDisposition.Sentinel,
                    true,
                    speed: 1f,
                    radius: 1f,
                    sight: 1f,
                    angle: -1f,
                    hearing: 1f,
                    sensitivity: 1f,
                    threshold: 1f,
                    investigate: 1f,
                    alert: false,
                    alertRadius: 0f,
                    alertCooldown: 3f,
                    alertAwareness: EnemyAwarenessState.Engaged,
                    windup: 1f,
                    active: 1f,
                    recovery: 1f,
                    hitArcBonus: 0f,
                    poiseOffset: 0,
                    ideal: 1f,
                    closeTolerance: 0.2f,
                    longTolerance: 0.35f,
                    pressureBias: 0.35f,
                    resets: 1,
                    notes: "Bosses are visible here for future planning; this tool does not change boss runtime behavior.")
            };
        }

        private static EnemyAiBrainTemplateDefinition Template(
            string id,
            string displayName,
            string description,
            EnemyAiBrainTemplateRole role,
            IEnumerable<EnemyBehaviorId> behaviors,
            IEnumerable<EnemyInstinctDisposition> dispositions,
            EnemyIntelligenceLevel intelligence,
            EnemyInstinctDisposition disposition,
            bool bossMetadataOnly,
            float speed,
            float radius,
            float sight,
            float angle,
            float hearing,
            float sensitivity,
            float threshold,
            float investigate,
            bool alert,
            float alertRadius,
            float alertCooldown,
            EnemyAwarenessState alertAwareness,
            float windup,
            float active,
            float recovery,
            float hitArcBonus,
            int poiseOffset,
            float ideal,
            float closeTolerance,
            float longTolerance,
            float pressureBias,
            int resets,
            string notes)
        {
            var template = ScriptableObject.CreateInstance<EnemyAiBrainTemplateDefinition>();
            template.name = id;
            template.Configure(
                id,
                displayName,
                description,
                role,
                behaviors,
                dispositions,
                intelligence,
                disposition,
                bossMetadataOnly,
                speed,
                radius,
                sight,
                angle,
                hearing,
                sensitivity,
                threshold,
                investigate,
                alert,
                alertRadius,
                alertCooldown,
                alertAwareness,
                windup,
                active,
                recovery,
                hitArcBonus,
                poiseOffset,
                ideal,
                closeTolerance,
                longTolerance,
                pressureBias,
                resets,
                notes);
            return template;
        }

        private static string SanitizeFileName(string value)
        {
            var invalid = Path.GetInvalidFileNameChars();
            return new string((value ?? "template").Select(character => invalid.Contains(character) ? '_' : character).ToArray());
        }
    }
}
