namespace Hollow.RoomDesigner
{
    public enum RoomDesignerTool
    {
        Ground = 0,
        Hole = 1,
        Rock = 2,
        EnemySpawn = 3,
        RewardSpawn = 4,
        ActiveDoor = 5,
        SecretDoor = 6,
        Erase = 7,
        Eyedropper = 8,
        SafeStart = 9,
        EnemyNormal = 10,
        EnemyFlying = 11,
        EnemyFast = 12,
        EnemyHeavy = 13,
        EnemyCharger = 14,
        EnemyTurret = 15,
        EnemySplitter = 16,
        InactiveDoor = 17,
        Spike = 18,
        StandardBarrel = 19,
        ExplosiveBarrel = 20,
        ChestSpawn = 21,
        EnemySpittingPod = 22,
        EnemyRat = 23,
        EnemySpider = 24,
        EnemySkeletonSword = 25,
        EnemySkeletonSpear = 26,
        EnemyKnight = 27,
        EnemyGiant = 28,
        EnemyHollowBird = 29,
        EnemyHollowBeast = 30,
        EnemyHollowArcher = 31,
        EnemyPowderGunner = 32,
        EnemyKnifeThrower = 33,
        EnemyRepeaterTurret = 34,
        EnemyClockworkSentry = 35,
        EnemyHollowAcolyte = 36,
        EnemyWraith = 37,
        EnemySoulEater = 38,
        EnemyCurseBinder = 39,
        EnemyGraveLantern = 40,
        EnemyStarforgedOctantSentry = 41,
        EnemyCrimsonRailSpider = 42,
        EnemyAzureMinigunTurret = 43,
        DecorGrassTuft = 44,
        DecorCrystalCluster = 45,
        DecorSmallTree = 46,
        DecorStoneRuin = 47,
        CorruptedChestSpawn = 48,
        GoldenChestSpawn = 49,
        EnemyEscapist = 50
    }
}
